### ISSUE TITLE
BindingError: Missing binding for type: 'Pv' typeId: 1788744

### ISSUE THREAD

**Issue by mifwarior** [ted537/tsembind#13]
/tmp/emscripten_temp_f3blvvj1/tsgen_a.out.js:122
      throw ex;
      ^

BindingError: Missing binding for type: 'Pv' typeId: 1788744
    at throwBindingError (/tmp/emscripten_temp_f3blvvj1/tsgen_a.out.js:4975:48)
    at embindEmitTypes (/tmp/emscripten_temp_f3blvvj1/tsgen_a.out.js:9375:9)
    at callRuntimeCallbacks (/tmp/emscripten_temp_f3blvvj1/tsgen_a.out.js:4387:26)
    at initRuntime (/tmp/emscripten_temp_f3blvvj1/tsgen_a.out.js:326:3)
    at doRun (/tmp/emscripten_temp_f3blvvj1/tsgen_a.out.js:10298:5)
    at run (/tmp/emscripten_temp_f3blvvj1/tsgen_a.out.js:10319:5)
    at runCaller (/tmp/emscripten_temp_f3blvvj1/tsgen_a.out.js:10252:19)
    at removeRunDependency (/tmp/emscripten_temp_f3blvvj1/tsgen_a.out.js:420:7)
    at receiveInstance (/tmp/emscripten_temp_f3blvvj1/tsgen_a.out.js:614:5)
    at receiveInstantiationResult (/tmp/emscripten_temp_f3blvvj1/tsgen_a.out.js:626:5)
em++: error: '/home/yura/Work/emsdk/node/16.20.0_64bit/bin/node /tmp/emscripten_temp_f3blvvj1/tsgen_a.out.js' failed (returned 7)

I'm using Embind and I don't have any "Pv" types. The project is built without the "--embind-emit-tsd" flag successfully.

How can I check where exactly the error is?

**Comment by mifwarior** [comment]
Link options:
set_target_properties(${name} PROPERTIES LINK_FLAGS "-sFORCE_FILESYSTEM=1 -sFETCH_SUPPORT_INDEXEDDB --indexedDB-name=drawingDb -lidbfs.js -sMAXIMUM_MEMORY=4GB -O1 -s ALLOW_MEMORY_GROWTH=1 -s NO_EXIT_RUNTIME=1 -s WASM=1 -s ERROR_ON_UNDEFINED_SYMBOLS=1 --use-preload-plugins --bind --embed-file ${ODA_BIN_DIR}/adinit.dat@adinit.dat --embind-emit-tsd ${ODA_BIN_DIR}/drawingjs.d.ts")

**Comment by ted537** [comment]
The `--embind-emit-tsd` is actually unrelated to this project, as that feature was added after this project was created. I imagine you'll want to create an issue somewhere in the core `emscripten` library for this. Best of luck!
